#!/bin/env sh


css="scriptgen.css"
html="scriptgen.html"

rm -f $css $html

fontpath="cm-unicode"




echo "/* Generated by weird bash script at $(date) */" >> $css
echo "/* It barely works, hardcoded paths etc. */" >> $css
for font in ${fontpath}/*; do
	name="${font#*/}"
	name="${name%.*}"
	echo "@font-face {" >> $css
	echo "	font-family: \"$name\";" >> $css
	echo "	src: url(\"$font\") format(\"truetype\");" >> $css
	echo "}" >> $css
	echo "#div-$name {" >> $css
	echo "	font-family: \"$name\";" >> $css
	echo "	font-size: 30pt;" >> $css
	echo "}" >> $css
done


echo "<!DOCTYPE html>" >> $html
echo "<!-- Generated by weird bash script at $(date) -->" >> $html
echo "<!-- It barely works, hardcoded paths etc. -->" >> $html
echo "<html>" >> $html
echo "	<head>" >> $html
echo "		<link rel=\"stylesheet\", href=\"$css\">" >> $html
echo "	</head>" >> $html
echo "	<body>" >> $html

for font in ${fontpath}/*; do
	name="${font#*/}"
	name="${name%.*}"
	echo "	<div id=\"div-$name\">" >> $html
	echo "	<h6>$name</h6>" >> $html
	echo "	The quick fox jumps over the lazy dog" >> $html
	echo "	</div>" >> $html
done
echo "	</body>" >> $html
echo "</html>" >> $html
